from django import forms

#osChoiceList = (('', 'Select os'),('ubuntu1804', 'ubuntu1804'),('centos','centos'),('RedHat','RedHat'),('Alinux','Alinux'))
osChoiceList = (('ubuntu1804', 'ubuntu1804'),('centos','centos'),('RedHat','RedHat'),('Alinux','Alinux'))
#masinstancetypelist = (('', 'Select Instance Type for Master Node'),('c5.xlarge', 'c5.xlarge'),('m4.large', 'm4.large'),('c5-24x', 'c5.24xlarge'))
masinstancetypelist = (('c5.xlarge', 'c5.xlarge'),('m4.large', 'm4.large'),('c5.24xlarge', 'c5.24xlarge'))
#MaxComputeNodes = (('', 'Select Maximum Count for Partition'),('5', '5'),('10', '10'),('15', '15'),('20', '20'))
MaxComputeNodes = (('5', '5'),('10', '10'),('15', '15'),('20', '20'))
#Nodetypelist = (('', 'Select Instance Type for Node'),('c6i.32xlarge', 'c6i.32xlarge'),('c6i.8xlarge', 'c6i.8xlarge'),('c5.xlarge', 'c5.xlarge'),('g4dn.xlarge','g4dn.xlarge'),('g5.2xlarge', 'g5.2xlarge'))
Nodetypelist = (('c6i.32xlarge', 'c6i.32xlarge'),('c6i.8xlarge', 'c6i.8xlarge'),('c5.xlarge', 'c5.xlarge'),('g4dn.xlarge','g4dn.xlarge'),('g5.2xlarge', 'g5.2xlarge'))
Relion_Versionlist = (('relion3.1.3', '3.1.3'),('relion3.1.2', '3.1.2'))
booleanChoices = (('yes','yes'),('no','no'))
#schedulerlist = (('', 'Select Scheduler'),('slurm','slurm'),('torque','torque'),('sge','sge'))
schedulerlist = (('slurm','slurm'),('torque','torque'),('sge','sge'))
PackageList = (('Intelmpi','intelmpi'),('mpich','mpich'),('openmpi','openmpi'),('mcr', 'MotionCor'),('ctf', 'ctffind'),('rsmp', 'Resmap'),('fltk', 'FLTK'),('fft', 'FFTW'),('libtiff','libtiff'),('singularity','singularity'))
#FSX_Lustre_Storage_Capacity_List = (('', 'Select Storage Capacity for Lustre FileSystem (in GiBs)'),(1200,"1200"),(2400,"2400"),(4800,"4800"),(7200,"7200"),(9600,"9600"),(12000,"12000"),(14400,"14400"))
FSX_Lustre_Storage_Capacity_List = ((1200,"1200"),(2400,"2400"),(4800,"4800"),(7200,"7200"),(9600,"9600"),(12000,"12000"),(14400,"14400"))
class ClusterForm(forms.Form):
        os = forms.ChoiceField(choices=osChoiceList,widget=forms.Select(attrs={'id': 'os'}))
        Relion_Version = forms.ChoiceField(choices=Relion_Versionlist,widget=forms.RadioSelect)
        Scheduler = forms.ChoiceField(choices=schedulerlist,widget=forms.Select(attrs={'id': 'scheduler'}))
        Master_Machine = forms.ChoiceField(label="Master Machine",choices=masinstancetypelist,widget=forms.Select(attrs={'id': 'master'}))
        Compute1_Machine = forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'compute1'}))
        Compute1_Machine_Count=forms.ChoiceField(choices=MaxComputeNodes,widget=forms.Select(attrs={'id': 'computecount1'}))
        Compute2_Machine=forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'compute2'}))
        Compute2_Machine_Count=forms.ChoiceField(choices=MaxComputeNodes,widget=forms.Select(attrs={'id': 'computecount2'}))
        Compute3_Machine=forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'compute3'}))
        Compute3_Machine_Count=forms.ChoiceField(choices=MaxComputeNodes,widget=forms.Select(attrs={'id': 'computecount3'}))
        Compute4_Machine=forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'compute4'}))
        Compute4_Machine_Count=forms.ChoiceField(choices=MaxComputeNodes,widget=forms.Select(attrs={'id': 'computecount4'}))
        Compute5_Machine=forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'compute5'}))
        Compute5_Machine_Count=forms.ChoiceField(choices=MaxComputeNodes,widget=forms.Select(attrs={'id': 'computecount5'}))
        FSX_Lustre_S3_Bucket_Name = forms.CharField(help_text="Enter S3 Bucket Name for Data",widget=forms.TextInput(attrs={'id': 's3bucketname'}))
        FSX_Lustre_S3_Bucket_Prefix = forms.CharField(required=False, help_text="Enter s3 bucket Prefix containing Data. Ex: dataA/dataB (Optional)",widget=forms.TextInput(attrs={'id': 's3bucketprefix'}))
        FSX_Lustre_Storage_Capacity=forms.ChoiceField(choices=FSX_Lustre_Storage_Capacity_List,widget=forms.Select(attrs={'id': 'storage'}))

class SingleNodeForm(forms.Form):
        Compute = forms.ChoiceField(choices=Nodetypelist,widget=forms.Select(attrs={'id': 'qclassid'}))
        os = forms.ChoiceField(choices=osChoiceList)
        Relion_Version = forms.ChoiceField(choices=Relion_Versionlist, widget=forms.RadioSelect)
        FSX_Lustre_S3_Bucket_Name = forms.CharField(help_text="Enter S3 Bucket Name for Data")
        FSX_Lustre_S3_Bucket_Prefix = forms.CharField(required=False, help_text="Enter s3 bucket Prefix containing Data. Ex: dataA/dataB (Optional)")
        FSX_Lustre_Storage_Capacity=forms.ChoiceField(choices=FSX_Lustre_Storage_Capacity_List,widget=forms.Select(attrs={'id': 'sclassid'}))
